version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./:/app"
    links:
      - sqlite
    ports:
      - 3000:3000

  migrate-db:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./:/app"
    links:
      - sqlite
    command: npm run migrate:up

  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/var/lib/sqlite/data
    environment:
      - SQLITE_USER=sqlite
      - SQLITE_PASSWORD=sqlite
      - SQLITE_DB=sqlite
    ports:
      - 5432:5432

  migrate:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - sqlite
    command: npm run migrate:up
